-- ==============================================================================
-- SMART WATER USAGE ADVISOR - POSTGRESQL AUTHORITATIVE SCHEMA (12 TABLES)
-- ==============================================================================
-- UN Sustainable Development Goal 6 (Clean Water & Sanitation)
-- Translates MySQL source concepts into robust, transaction-safe PostgreSQL DDL.
-- ==============================================================================

BEGIN;

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    user_type VARCHAR(50) NOT NULL CHECK (user_type IN ('household', 'institution', 'municipal')),
    city VARCHAR(100),
    country VARCHAR(100) DEFAULT 'India',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

-- 2. METERS TABLE
CREATE TABLE IF NOT EXISTS meters (
    meter_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    meter_serial_number VARCHAR(100) UNIQUE NOT NULL,
    meter_type VARCHAR(50) NOT NULL CHECK (meter_type IN ('smart', 'digital', 'analog')),
    installation_date DATE NOT NULL,
    manufacturer VARCHAR(100),
    api_key VARCHAR(255),
    api_endpoint VARCHAR(255),
    location_description VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. USER PROFILES TABLE
CREATE TABLE IF NOT EXISTS user_profiles (
    profile_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    household_size INTEGER DEFAULT 1 CHECK (household_size >= 1),
    property_type VARCHAR(50) NOT NULL CHECK (property_type IN ('apartment', 'house', 'commercial')),
    property_area_sqm NUMERIC(10, 2) DEFAULT 0.00,
    has_garden BOOLEAN DEFAULT FALSE,
    has_swimming_pool BOOLEAN DEFAULT FALSE,
    water_source VARCHAR(50) DEFAULT 'municipal' CHECK (water_source IN ('municipal', 'groundwater', 'mixed')),
    annual_income_range VARCHAR(50),
    occupancy_type VARCHAR(50) DEFAULT 'full-time' CHECK (occupancy_type IN ('full-time', 'part-time', 'seasonal')),
    conservation_priority VARCHAR(50) DEFAULT 'medium' CHECK (conservation_priority IN ('high', 'medium', 'low')),
    preferred_communication_language VARCHAR(50) DEFAULT 'en',
    privacy_level VARCHAR(50) DEFAULT 'standard'
);

-- 4. WATER USAGE DATA TABLE
CREATE TABLE IF NOT EXISTS water_usage_data (
    reading_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id INTEGER NOT NULL REFERENCES meters(meter_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    cumulative_reading NUMERIC(12, 3) NOT NULL CHECK (cumulative_reading >= 0),
    hourly_consumption_liters NUMERIC(10, 3) NOT NULL CHECK (hourly_consumption_liters >= 0),
    daily_consumption_liters NUMERIC(10, 3) CHECK (daily_consumption_liters >= 0),
    monthly_consumption_liters NUMERIC(12, 3) CHECK (monthly_consumption_liters >= 0),
    temperature_celsius NUMERIC(5, 2),
    quality_score INTEGER DEFAULT 100 CHECK (quality_score >= 0 AND quality_score <= 100),
    data_source VARCHAR(50) NOT NULL CHECK (data_source IN ('api', 'manual', 'estimated')),
    is_validated BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_meter_timestamp UNIQUE (meter_id, timestamp)
);

-- 5. CONSUMPTION CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS consumption_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category_name VARCHAR(50) NOT NULL CHECK (category_name IN ('bathroom', 'kitchen', 'laundry', 'garden', 'cleaning', 'other')),
    date DATE NOT NULL,
    estimated_liters NUMERIC(10, 3) NOT NULL CHECK (estimated_liters >= 0),
    percentage_of_daily NUMERIC(5, 2) NOT NULL CHECK (percentage_of_daily >= 0 AND percentage_of_daily <= 100),
    estimation_method VARCHAR(50) DEFAULT 'heuristic_profile_disaggregation'
);

-- 6. PREDICTIONS TABLE (For Phase 3 ML Model Integration)
CREATE TABLE IF NOT EXISTS predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id INTEGER NOT NULL REFERENCES meters(meter_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    prediction_date DATE NOT NULL,
    predicted_daily_liters NUMERIC(10, 3) NOT NULL CHECK (predicted_daily_liters >= 0),
    predicted_weekly_liters NUMERIC(12, 3),
    predicted_monthly_liters NUMERIC(12, 3),
    confidence_score NUMERIC(5, 4) CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
    model_version VARCHAR(50) NOT NULL,
    prediction_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. ANOMALIES TABLE (For Phase 3 Anomaly/Leak Detection)
CREATE TABLE IF NOT EXISTS anomalies (
    anomaly_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id INTEGER NOT NULL REFERENCES meters(meter_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    detection_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    anomaly_type VARCHAR(50) NOT NULL CHECK (anomaly_type IN ('leak', 'surge', 'low', 'unusual_pattern')),
    consumption_value NUMERIC(10, 3) NOT NULL,
    expected_value NUMERIC(10, 3) NOT NULL,
    deviation_percentage NUMERIC(8, 2),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    leak_probability_score NUMERIC(5, 4) CHECK (leak_probability_score >= 0.0 AND leak_probability_score <= 1.0),
    alert_sent BOOLEAN DEFAULT FALSE,
    alert_timestamp TIMESTAMP WITH TIME ZONE,
    user_acknowledged BOOLEAN DEFAULT FALSE,
    resolution_status VARCHAR(50) DEFAULT 'pending' CHECK (resolution_status IN ('pending', 'investigating', 'resolved', 'false_alarm'))
);

-- 8. RECOMMENDATIONS TABLE
CREATE TABLE IF NOT EXISTS recommendations (
    recommendation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    recommendation_type VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    estimated_savings_liters NUMERIC(10, 2) DEFAULT 0.00,
    estimated_savings_amount NUMERIC(10, 2) DEFAULT 0.00,
    priority VARCHAR(20) NOT NULL CHECK (priority IN ('critical', 'high', 'medium', 'low')),
    implementation_difficulty VARCHAR(20) DEFAULT 'easy' CHECK (implementation_difficulty IN ('easy', 'medium', 'hard')),
    generated_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    user_action VARCHAR(50) DEFAULT 'none' CHECK (user_action IN ('none', 'viewed', 'in_progress', 'completed', 'dismissed')),
    action_timestamp TIMESTAMP WITH TIME ZONE,
    feedback_score INTEGER CHECK (feedback_score >= 1 AND feedback_score <= 5)
);

-- 9. ALERTS TABLE
CREATE TABLE IF NOT EXISTS alerts (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    alert_type VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    related_id BIGINT,
    related_type VARCHAR(50),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    created_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN DEFAULT FALSE,
    read_timestamp TIMESTAMP WITH TIME ZONE,
    action_url VARCHAR(255)
);

-- 10. GOALS TABLE
CREATE TABLE IF NOT EXISTS goals (
    goal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    goal_type VARCHAR(50) NOT NULL CHECK (goal_type IN ('daily_limit', 'weekly_target', 'savings_amount', 'percentage_reduction')),
    target_value NUMERIC(10, 2) NOT NULL CHECK (target_value > 0),
    target_unit VARCHAR(20) NOT NULL DEFAULT 'liters',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    progress_percentage NUMERIC(5, 2) DEFAULT 0.00 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
    status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'achieved', 'missed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 11. FEEDBACK TABLE
CREATE TABLE IF NOT EXISTS feedback (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    feedback_type VARCHAR(100) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    response_or_suggestion TEXT,
    is_actionable BOOLEAN DEFAULT TRUE,
    status VARCHAR(50) DEFAULT 'submitted' CHECK (status IN ('submitted', 'under_review', 'resolved', 'closed')),
    created_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    resolved_timestamp TIMESTAMP WITH TIME ZONE
);

-- 12. CHATBOT CONVERSATIONS TABLE
CREATE TABLE IF NOT EXISTS chatbot_conversations (
    conversation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    session_id VARCHAR(100) NOT NULL,
    turn_number INTEGER NOT NULL DEFAULT 1,
    user_message TEXT NOT NULL,
    chatbot_response TEXT NOT NULL,
    intent_detected VARCHAR(100),
    confidence_score NUMERIC(5, 4),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    was_helpful BOOLEAN
);

-- ==============================================================================
-- HIGH-PERFORMANCE INDEXES
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_water_usage_meter_time ON water_usage_data(meter_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_water_usage_user_time ON water_usage_data(user_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_water_usage_timestamp ON water_usage_data(timestamp);
CREATE INDEX IF NOT EXISTS idx_anomalies_meter_time ON anomalies(meter_id, detection_timestamp);
CREATE INDEX IF NOT EXISTS idx_anomalies_severity ON anomalies(severity);
CREATE INDEX IF NOT EXISTS idx_recommendations_user_time ON recommendations(user_id, generated_timestamp);
CREATE INDEX IF NOT EXISTS idx_recommendations_priority ON recommendations(priority);
CREATE INDEX IF NOT EXISTS idx_alerts_user_read ON alerts(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_alerts_created_time ON alerts(created_timestamp);
CREATE INDEX IF NOT EXISTS idx_goals_user_status ON goals(user_id, status);
CREATE INDEX IF NOT EXISTS idx_chatbot_user_session ON chatbot_conversations(user_id, session_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_timestamp ON chatbot_conversations(timestamp);

COMMIT;
