-- ==============================================================================
-- SMART WATER USAGE ADVISOR - PHASE 7 SCHEMA MIGRATION
-- ==============================================================================
-- Adds:
-- 1. Alert Resolution Tracking columns to alerts
-- 2. Scenarios table for What-If Scenario Analysis
-- 3. Water Budgets table for Water Budget Planner
-- 4. Performance indexes
-- ==============================================================================

BEGIN;

-- 1. Extend ALERTS table with resolution workflow columns
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'NEW' CHECK (status IN ('NEW', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED'));
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS acknowledged_timestamp TIMESTAMP WITH TIME ZONE;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS resolved_timestamp TIMESTAMP WITH TIME ZONE;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS resolution_note TEXT;
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS resolved_by_user_id INTEGER REFERENCES users(user_id);

-- 2. Create SCENARIOS table
CREATE TABLE IF NOT EXISTS scenarios (
    scenario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    scenario_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    percentage_change NUMERIC(5, 2) NOT NULL,
    baseline_liters NUMERIC(10, 3) NOT NULL,
    scenario_liters NUMERIC(10, 3) NOT NULL,
    saved_liters NUMERIC(10, 3) NOT NULL,
    estimated_savings_amount NUMERIC(10, 2) DEFAULT 0.00,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create WATER_BUDGETS table
CREATE TABLE IF NOT EXISTS water_budgets (
    budget_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    period VARCHAR(20) NOT NULL CHECK (period IN ('daily', 'weekly', 'monthly')),
    target_liters NUMERIC(10, 2) NOT NULL CHECK (target_liters > 0),
    cost_budget NUMERIC(10, 2),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Indexes
CREATE INDEX IF NOT EXISTS idx_alerts_user_status ON alerts(user_id, status);
CREATE INDEX IF NOT EXISTS idx_scenarios_user_time ON scenarios(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_budgets_user_active ON water_budgets(user_id, is_active);

COMMIT;
